crudapp/crudapp/urls.py
from django.contrib import admin
from django.urls import path
from business import views  

urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('create', views.create, name='create'),  
    path('',views.show,name='show'),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.delete),  
]  

crudapp/business/models.py
from django.db import models

# Create your models here.
class Business(models.Model):  
    bid = models.CharField(max_length=20,unique=True)  
    bname = models.CharField(max_length=100)  
    bemail = models.EmailField()  
    bownerinfo = models.CharField(max_length=100)
    baddressl1 = models.CharField(max_length=100)  
    baddressl2 = models.CharField(max_length=100) 
    bsize = models.IntegerField()
    class Meta:  
        db_table = "business"  

crudapp/business/forms.py
from django import forms  
from business.models import Business  
class BusinessForm(forms.ModelForm):  
    class Meta:  
        model = Business  
        fields = "__all__"  

crudapp/business/views.py
from django.shortcuts import render, redirect  
from business.forms import BusinessForm  
from business.models import Business  
# Create your views here.  
def create(request):  
    if request.method == "POST":  
        form = BusinessForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/')  
            except:  
                pass  
    else:  
        form = BusinessForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    Businesss = Business.objects.all()  
    return render(request,"show.html",{'Businesss':Businesss})  
def edit(request, id):  
    Busines = Business.objects.get(bid=id)  
    return render(request,'edit.html', {'Business':Busines})  
def update(request, id):  
    Busines = Business.objects.get(bid=id)  
    form = BusinessForm(request.POST, instance = Busines)  
    if form.is_valid():  
        form.save()  
        return redirect("/")  
    return render(request, 'edit.html', {'Business': Busines})  
def delete(request, id):  
    Busines = Business.objects.get(bid=id)  
    Busines.delete()  
    return redirect("/")  

# Create your views here.

crudapp/business/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{business.bid}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="bid" id="id_bid" required maxlength="20" value="{{ business.bid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="bname" id="id_bname" required maxlength="100" value="{{ business.bname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="bemail" id="id_bemail" required maxlength="254" value="{{ business.bemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business bownerinfo:</label>  
    <div class="col-sm-4">  
        <input type="text" name="bownerinfo" id="id_bownerinfo" required maxlength="15" value="{{ business.bownerinfo }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business baddressl1:</label>  
    <div class="col-sm-4">  
        <input type="text" name="baddressl1" id="id_baddressl1" required maxlength="15" value="{{ business.baddressl1 }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business baddressl2:</label>  
    <div class="col-sm-4">  
        <input type="text" name="baddressl2" id="id_baddressl2" required maxlength="15" value="{{ business.baddressl2 }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business bsize:</label>  
    <div class="col-sm-4">  
        <input type="number" name="bsize" id="id_bsize" required maxlength="15" value="{{ business.bsize }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

crudapp/business/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/create">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Id:</label>  
    <div class="col-sm-4">  
      {{ form.bid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Name:</label>  
    <div class="col-sm-4">  
      {{ form.bname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Email:</label>  
    <div class="col-sm-4">  
      {{ form.bemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Owner Info:</label>  
    <div class="col-sm-4">  
      {{ form.bownerinfo }}  
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Address Line1:</label>  
    <div class="col-sm-4">  
      {{ form.baddressl1 }}  
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Address Line2:</label>  
    <div class="col-sm-4">  
      {{ form.baddressl2 }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Size:</label>  
    <div class="col-sm-4">  
      {{ form.bsize }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

crudapp/business/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Business Details</title>  
     {% load static %}  
     {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Business ID</th>  
        <th>Business Name</th>  
        <th>Business Email</th>  
        <th>Business Owner Info</th>
        <th>Business Address L1</th>
        <th>Business Address L2</th>
        <th>Business Size</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for business in Businesss %}  
    <tr>  
        <td>{{ business.bid }}</td>  
        <td>{{ business.bname }}</td>  
        <td>{{ business.bemail }}</td>  
        <td>{{ business.bownerinfo }}</td>
        <td>{{ business.baddressl1 }}</td>
        <td>{{ business.baddressl2 }}</td>  
        <td>{{ business.bsize }}</td>  
        <td>  
            <a href="/edit/{{ business.bid }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ business.bid }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/create" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  